### ISSUE TITLE
Doesn't compile under go 1.15.1

### ISSUE THREAD

**Issue by mk23** [ashb/jqrepl#13]
Worked fine with 1.14.8, but under 1.15.1 throws this error:
```
# github.com/ashb/jqrepl/jq
_cgo_export.c:29:3: error: unknown type name 'jv'
```
